# Generated by Django 5.2.3 on 2025-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='payslip_upload',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='photo_upload',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='resume_upload',
            field=models.FileField(upload_to='images'),
        ),
    ]
