# Generated by Django 5.2.3 on 2025-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0002_alter_emp_payslip_upload_alter_emp_photo_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='tech_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='topic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
