# Generated by Django 5.2.3 on 2025-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0003_alter_emp_score_alter_emp_tech_score_alter_emp_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
