# Generated by Django 5.2.3 on 2025-06-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0004_alter_emp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='dob',
            field=models.DateField(),
        ),
    ]
