# Generated by Django 5.2.3 on 2025-06-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0006_alter_emp_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='dob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
