# Generated by Django 5.2.3 on 2025-06-27 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0007_alter_emp_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('gmail', models.EmailField(max_length=255, unique=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=20, null=True)),
                ('tech_score', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other')], max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('position_applied', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Networking', 'Networking'), ('Digital Marketing', 'Digital Marketing'), ('Operations', 'Operations'), ('Sales', 'Sales'), ('Other', 'Other')], max_length=20)),
                ('ug_qualification', models.CharField(max_length=255)),
                ('ug_category', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_graduation', models.CharField(max_length=4)),
                ('current_employer', models.CharField(max_length=255)),
                ('total_experience', models.CharField(max_length=100)),
                ('relevant_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_certifications', models.TextField(blank=True, null=True)),
                ('pg_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_pg_graduation', models.CharField(blank=True, max_length=4, null=True)),
                ('resume_upload', models.FileField(upload_to='images')),
                ('photo_upload', models.ImageField(upload_to='images')),
                ('degrees', models.CharField(blank=True, help_text='Comma-separated: UG,PG,Diploma', max_length=100, null=True)),
                ('pg_degree_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_category', models.CharField(blank=True, max_length=255, null=True)),
                ('payslip_upload', models.FileField(blank=True, upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
