# Generated by Django 5.2.3 on 2025-06-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0008_candidate_delete_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
