# Generated by Django 5.2.3 on 2025-07-08 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0011_candidate_dob_alter_candidate_current_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
