# Generated by Django 5.2.3 on 2025-07-11 08:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0012_phoneotpverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits')])),
                ('company_social_media_Linkedin', models.JSONField(blank=True, default=list)),
                ('company_social_media_Instagram', models.JSONField(blank=True, default=list)),
                ('company_social_media_Facebook', models.JSONField(blank=True, default=list)),
                ('company_social_media_Twitter', models.JSONField(blank=True, default=list)),
                ('company_social_media_Whatsapp_group', models.JSONField(blank=True, default=list)),
                ('company_department', models.CharField(blank=True, max_length=255, null=True)),
                ('company_employees', models.IntegerField()),
                ('company_weblink', models.URLField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_branch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('company_certification', models.CharField(blank=True, max_length=100, null=True)),
                ('company_license', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
