# Generated by Django 5.2.3 on 2025-07-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0013_companydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
