# Generated by Django 5.2.3 on 2025-08-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vien', '0015_openings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openings',
            name='status',
        ),
    ]
